name = "midimoni"
compatibility_date = "2024-01-01"

# Static site configuration
[site]
bucket = "./build/client"

[build]
command = "npm run build"

# Assets configuration
[assets]
directory = "./build/client"
binding = "ASSETS"

[vars]
NODE_ENV = "production"